version: "3.4"

services:
  db:
    image: postgres:14-bullseye
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpassword
    ports:
      - "5435:5432"
    volumes:
      - db:/var/lib/postgresql/data:rw

volumes:
  db:
